language: python
python:
 - 3.6
global:
 -DEBUG=True
install:
 - pip install -q -r requirements-dev.txt codecov
script:
 - flake8
 - pytest django_blog --cov=django_blog/core/test
after_success:
 - codecov